### ISSUE TITLE
What is the difference between "tencent.com/vcuda-core" and "tencent.com/vcuda-core-limit"

### ISSUE THREAD

**Issue by shanshuiguochu** [tkestack/gpu-manager#10]
the values of tencent.com/vcuda-core and  tencent.com/vcuda-core-limit are the same.
If tencent.com/vcuda-core < 100, the gpu is shared mode, so tencent.com/vcuda-core-limit is no useful.

**Comment by mYmNeo** [comment]
`tencent.com/vcuda-core` is written in resource field in container spec, `tencent.com/vcuda-core-limit` is written in annotation in Pod spec. They're not the same, the former means the least resource to be guaranteed, the latter means the most resource all containers can use.

**Comment by shanshuiguochu** [comment]
Thank @mYmNeo for your answer！

Since [vcudaConfig.utilization = C.int(cores)](https://github.com/tkestack/gpu-manager/blob/master/pkg/services/virtual-manager/manager.go#L575) and [vcudaConfig.limit = C.int(limitCores)](https://github.com/tkestack/gpu-manager/blob/master/pkg/services/virtual-manager/manager.go#L588) are both in [for _, cont := range pod.Spec.Containers ](https://github.com/tkestack/gpu-manager/blob/master/pkg/services/virtual-manager/manager.go#L553), ` tencent.com/vcuda-core-limit ` and ` tencent.com/vcuda-core ` are both work on container(s) in the same pod. So the least resource is the same and the most resource is different on container(s) in the same pod.
Is this statement right?
If right, why the least resource is the same on container(s) in the same pod?
In other word, why not designed like this:
```yaml
containers:
- image: <a-image>
  resources:
    limits:
        tencent.com/vcuda-core-limit: 30
        tencent.com/vcuda-core: 40
- image: <b-image>
  resources:
    limits:
        tencent.com/vcuda-core-limit: 50
        tencent.com/vcuda-core: 60
```
