### ISSUE TITLE
No metric collected when no "tencent.com/vcuda-core"  assigned

### ISSUE THREAD

**Issue by xiaoFine** [tkestack/gpu-manager#173]
I deployed my app via SeldonCore and Triton Server in an k8s, and found no metrics collected when `tencent.com/vcuda-core` is skipped in deployment.yaml. Is that a bug or  the `tencent.com/vcuda-core` must be configed for each deployment?

```yaml
### metrics are collected when configed like this
Resources:
    Limits:
         tencent.com/vcuda-core:    50
         tencent.com/vcuda-memory:  3
    Requests:
          tencent.com/vcuda-core:    50
          tencent.com/vcuda-memory:  3
```

```yaml
### metrics are not collected when no vcuda-core set
Resources:
    Limits:
         tencent.com/vcuda-memory:  3
    Requests:
          tencent.com/vcuda-memory:  3
```
