### ISSUE TITLE
请问如何实现文章中提到的 Elastic Resource Allocation

### ISSUE THREAD

**Issue by scxu** [tkestack/gpu-manager#19]
如下图所示：

![image](https://user-images.githubusercontent.com/27944120/79486929-0c44eb80-804a-11ea-9b52-8a6bafcb63b0.png)

文章中提及了这个动态资源分配的能力，可是在 gpu-manager 的文档里需要保证 `requests` 和 `limits` 是固定的，是这个组件目前还不支持这个高级功能吗？

**Comment by mYmNeo** [comment]
Please read the README

**Comment by scxu** [comment]
@mYmNeo 

我看了 REAME 了，能否给一些更具体的提示呢？

```
apiVersion: v1
kind: Pod
metadata:
  name: vcuda
  annotation:
    tencent.com/vcuda-core-limit: 50
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
  - image: <test-image>
    name: nvidia
    command: ['/usr/local/nvidia/bin/nvidia-smi']
    resources:
      requests:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
      limits:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
```

请问这个如何设置成动态划分资源的呢？谢谢
