### ISSUE TITLE
pod pending with event: Insufficient tencent.com/vcuda-memory, etc.

### ISSUE THREAD

**Issue by sgybupt** [tkestack/gpu-manager#28]
Thanks for your work.
It occurs with 
```unknown field "annotation" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; ```
with yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: vcuda
  annotation:
    tencent.com/vcuda-core-limit: 100
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
  - image: tensorflow/tensorflow:latest-gpu-jupyter
    name: nvidia
    ports:
    - containerPort: 8888
      hostPort: 8888
    resources:
      requests:
        tencent.com/vcuda-core: 100
        tencent.com/vcuda-memory: 1
      limits:
        tencent.com/vcuda-core: 100
        tencent.com/vcuda-memory: 1
```
------
After remove the field annotations, cluster fail scheduling with error:
```
0/3 nodes are available: 3 Insufficient tencent.com/vcuda-core, 3 Insufficient tencent.com/vcuda-memory.
```
------
But I have 3 GPUs in that node and label this node.
Do you have some solutions?
