### ISSUE TITLE
Cannot submit a Pod 

### ISSUE THREAD

**Issue by Mier-aluo** [tkestack/gpu-manager#44]
After executing `make` and `meke img`, I set gpu-manager as daemonset, and follow the README to set the environment. 

When I submit a pod, I get an error as followed:

    error: unable to decode "test01.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 5, error found in #10 byte of ...|e-limit":50},"name":|..., bigger context ...|":{"annotations":{"tencent.com/vcuda-core-limit":50},"name":"vcuda"},"spec":{"containers":[{"command|...

Pod .yaml 
    
```
apiVersion: v1
kind: Pod
metadata:
  name: vcuda
  annotations:
    tencent.com/vcuda-core-limit: 50
spec:
  restartPolicy: Never
  containers:
  - image: tf1.15-backend:1.0
    name: nvidia
    command:
    - /usr/local/nvidia/bin/nvidia-smi
    - pmon
    - -d
    - 10
    resources:
      requests:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
      limits:
        tencent.com/vcuda-core: 50
        tencent.com/vcuda-memory: 30
```

I run the conmand  as non-root because my account is without `root`
