### ISSUE TITLE
Memory allocation exception

### ISSUE THREAD

**Issue by KarlCyan** [tkestack/gpu-manager#8]
## Describe 
When I give pod "1" vcuda-memory , it will use each gpu-device 256Mi gpu-memory . Does it limit the use of each GPU card or the total number of GPUs on the node?

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40	  Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:65:00.0 Off |                  N/A |
| 41%   31C    P2    33W / 225W |    267MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:B3:00.0 Off |                  N/A |
| 41%   31C    P2    46W / 225W |    243MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

### GPU Info :
GeForce RTX 2080 - 8G * 2

### Kubernetes
v1.13.2

## Test file
```
import tensorflow as tf
import timeit

with tf.device('/cpu:0'):
	cpu_a = tf.random.normal([10000, 1000])
	cpu_b = tf.random.normal([1000, 2000])
	print(cpu_a.device, cpu_b.device)

with tf.device('/gpu:0'):
	gpu_a = tf.random.normal([10000, 1000])
	gpu_b = tf.random.normal([1000, 2000])
	print(gpu_a.device, gpu_b.device)

def cpu_run():
	with tf.device('/cpu:0'):
		c = tf.matmul(cpu_a, cpu_b)
	return c

def gpu_run():
	with tf.device('/gpu:0'):
		c = tf.matmul(gpu_a, gpu_b)
	return c
# warm up
cpu_time = timeit.timeit(cpu_run, number=10)
gpu_time = timeit.timeit(gpu_run, number=10)
print('warmup:', cpu_time, gpu_time)

cpu_time = timeit.timeit(cpu_run, number=10)
gpu_time = timeit.timeit(gpu_run, number=10)
print('run time:', cpu_time, gpu_time)
```
## Resource Limit 
```
        resources:
          limits:
            tencent.com/vcuda-core: "30"
            tencent.com/vcuda-memory: "1"
          requests:
            tencent.com/vcuda-core: "30"
            tencent.com/vcuda-memory: "1"
```

**Comment by mYmNeo** [comment]
>When I give pod "1" vcuda-memory , it will use each gpu-device 256Mi gpu-memory . Does it limit the use of each GPU card or the total number of GPUs on the node?

If you set "1" vcuda-memory, It'll limit the use of memory of the card given to this container. But If you give the "privileged" permission to the Pod, it'll not work well.

**Comment by KarlCyan** [comment]
> > When I give pod "1" vcuda-memory , it will use each gpu-device 256Mi gpu-memory . Does it limit the use of each GPU card or the total number of GPUs on the node?
> 
> If you set "1" vcuda-memory, It'll limit the use of memory of the card given to this container. But If you give the "privileged" permission to the Pod, it'll not work well.

I just want to give "1" vcuda-memory to this container, but it uses 256MB of memory from two GPU CARDS on this node. This container actually has 512M of GPU memory.

**Comment by KarlCyan** [comment]
> > When I give pod "1" vcuda-memory , it will use each gpu-device 256Mi gpu-memory . Does it limit the use of each GPU card or the total number of GPUs on the node?
> 
> If you set "1" vcuda-memory, It'll limit the use of memory of the card given to this container. But If you give the "privileged" permission to the Pod, it'll not work well.

I just want to give "1" vcuda-memory to this container, but it uses 256M of GPU memory from two GPU CARDS on this node. This container actually has 512M of GPU memory.

**Comment by mYmNeo** [comment]
> > > When I give pod "1" vcuda-memory , it will use each gpu-device 256Mi gpu-memory . Does it limit the use of each GPU card or the total number of GPUs on the node?
> > 
> > 
> > If you set "1" vcuda-memory, It'll limit the use of memory of the card given to this container. But If you give the "privileged" permission to the Pod, it'll not work well.
> 
> I just want to give "1" vcuda-memory to this container, but it uses 256MB of memory from two GPU CARDS on this node. This container actually has 512M of GPU memory.

Could you paste your pod template and the environment variables that contain "NVIDIA" or "LD_LIBRARY_PATH"? And do you use native docker or nvidia-docker?

**Comment by KarlCyan** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tf
  name: tf
  namespace: gpu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tf
  strategy: {}
  template:
    metadata:
      labels:
        run: tf
    spec:
      dnsPolicy: Default
      containers:
      - image: tensorflow/tensorflow:devel-gpu
        command: ["sleep","3600000"]
        name: tf
        resources:
          requests:
            tencent.com/vcuda-core: 30
            tencent.com/vcuda-memory: 10
          limits:
            tencent.com/vcuda-core: 30
            tencent.com/vcuda-memory: 10
```
