### ISSUE TITLE
Extra flag option --container-runtime-endpoint doesn't work.

### ISSUE THREAD

**Issue by niteshsakhiya** [tkestack/gpu-manager#85]
I am trying to deploy the gpu-manager on AKS cluster for which container runtime is containerd. For the same, I am trying to use --container-runtime-endpoint flag to specify container runtime unix socket. The gpu-manager shows the following error.

```
copy /usr/local/host/bin/nvidia-cuda-mps-control to /usr/local/nvidia/bin/
copy /usr/local/host/bin/nvidia-cuda-mps-server to /usr/local/nvidia/bin/
copy /usr/local/host/bin/nvidia-debugdump to /usr/local/nvidia/bin/
copy /usr/local/host/bin/nvidia-persistenced to /usr/local/nvidia/bin/
copy /usr/local/host/bin/nvidia-smi to /usr/local/nvidia/bin/
rebuild ldcache
launch gpu manager
unknown flag: --container-runtime-endpoint
Usage of /usr/bin/gpu-manager:
unknown flag: --container-runtime-endpoint
      --allocation-check-period int      allocation check period, unit second (default 30)
      --alsologtostderr                  log to standard error as well as files
      --checkpoint-path string           configuration path for checkpoint store file (default "/etc/gpu-manager/checkpoint")
      --device-plugin-path string        the path for kubelet receive device plugin registration
      --docker-endpoint string           Use this for the docker endpoint to communicate with (default "unix:////var/run/docker.sock")
      --driver string                    The driver name for manager (default "nvidia")
      --extra-config string              The extra config file location
      --hostname-override string         If non-empty, will use this string as identification instead of the actual hostname.
      --incluster-mode                   Tell manager kubeconfig is built from in cluster token
      --kubeconfig string                Path to kubeconfig file with authorization information (the master location is set by the master flag).
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory (default "")
      --logtostderr                      log to standard error instead of files
      --node-labels string               automated label for this node, if empty, node will be only labeled by gpu model
      --query-addr string                address for query statistics information (default "localhost")
      --query-port int                   port for query statistics information (default 5678)
      --sample-period int                Sample period for each card, unit second (default 1)
      --share-mode                       enable share mode allocation
      --standalone                       Standalone mode(with no kubernetes API server
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs (default 0)
      --version version[=true]           Print version information and quit
      --virtual-manager-path string      configuration path for virtual manager store files (default "/etc/gpu-manager/vm")
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
      --volume-config string             The volume config file location

```

Daemonset specs:
```
          env:
            - name: LOG_LEVEL
              value: "4"
            - name: EXTRA_FLAGS
              value: "--logtostderr=false --container-runtime-endpoint=/var/run/containerd/containerd.sock"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

I also tried using --extra-config using a config map as a volume but I am not sure how the details should be specified in the config map file.

**Comment by niteshsakhiya** [comment]
The issue has been resolved. I was using older docker image.

**Comment by SinghDivneet** [comment]
@niteshsakhiya  which version resolved your issues?

**Comment by seanchen022** [comment]
@niteshsakhiya hi, could you tell me which version supports the containerd.

**Comment by niteshsakhiya** [comment]
@SinghDivneet @seanchen022 
I used the following docker image.
`tkestack/gpu-manager:v1.1.4`

**Comment by seanchen022** [comment]
@niteshsakhiya Thanks. I used your docker image, but i have the following errors when i execute command nvidia-smi in the gpu container created by gpu-manager, `F0627 08:01:53.251397      30 client.go:78] fail to get response from manager, error rpc error: code = Unknown desc = can't find containerd-fd006478ab2674c2a5d36fb0cf96f4807d393e46222ac63e1791b77ccf5635a9 from docker
/tmp/cuda-control/src/register.c:87 rpc client exit with 255`
 Do you know how to solve this problem?

**Comment by niteshsakhiya** [comment]
@seanchen022 
I am using the following DaemonSet definition. Make sure to use --container-runtime-endpoint value as per your node configs. Hope this helps. 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: gpu-manager
    meta.helm.sh/release-namespace: default
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gpu-manager-daemonset
  namespace: gpu-resources
spec:
  selector:
    matchLabels:
      name: gpu-manager-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: gpu-manager-ds
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: "5"
        - name: EXTRA_FLAGS
          value: --logtostderr=false --container-runtime-endpoint=/var/run/containerd/containerd.sock
            --cgroup-driver=systemd
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: tkestack/gpu-manager:v1.1.4
        imagePullPolicy: Always
        name: gpu-manager
        ports:
        - containerPort: 5678
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin
        - mountPath: /etc/gpu-manager/vdriver
          name: vdriver
        - mountPath: /etc/gpu-manager/vm
          name: vmdata
        - mountPath: /var/log/gpu-manager
          name: log
        - mountPath: /etc/gpu-manager/checkpoint
          name: checkpoint
        - mountPath: /var/run
          name: run-dir
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        - mountPath: /usr/local/host
          name: usr-directory
          readOnly: true
      dnsPolicy: ClusterFirst
      hostPID: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gpu-manager
      serviceAccountName: gpu-manager
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
        name: device-plugin
      - hostPath:
          path: /etc/gpu-manager/vm
          type: DirectoryOrCreate
        name: vmdata
      - hostPath:
          path: /etc/gpu-manager/vdriver
          type: DirectoryOrCreate
        name: vdriver
      - hostPath:
          path: /etc/gpu-manager/log
          type: DirectoryOrCreate
        name: log
      - hostPath:
          path: /etc/gpu-manager/checkpoint
          type: DirectoryOrCreate
        name: checkpoint
      - hostPath:
          path: /var/run
          type: Directory
        name: run-dir
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
      - hostPath:
          path: /usr
          type: Directory
        name: usr-directory
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```
